name: Just Another GHA

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: number
    
jobs:
  trying-splitting-steps:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - name: Failing maybe
        if: inputs.version == '9'
        run: exit 1
      - run: echo hello